In [3]:
import numpy as np

In [ ]:
# Q1. 3d array of shape (2,3,4) filled with int 1-24
ar1 = np.arange(1,25).reshape(2,3,4)
print(ar1)

# Q2. 5 x 5 with random iny 10-50, extract evens
evenarray = np.random.randint(10,50,size = (5,5))
even = evenarray[evenarray % 2 == 0]
print("\n Q2 \n",evenarray)
print("\n Even num :",even)

# Q3. Create two arrays a = np.arange(1,13).reshape(3,4) and b = np.array([10,20,30,40])
#     Use broadcasting to add b to each row of a
print("\n Q3 broadcasting to add b to each row of a \n")
a = np.arange(1,13).reshape(3,4)
b = np.array([10,20,30,40])
s = a + b
print(s)

# Q4. Construct a 6 x 6 identity matrix and replace its secondary diagonal (from top - right to bottol left)
print("\n Q6 replace secondary diagonal (from top-right to bottom-left)")
ar4 = np.eye(6,dtype=int)
print(ar4)
ar4[np.arange(6),np.arange(5,-1,-1)] = 7
print()
print(ar4)

# Q5. Generate 20 linearly spaced numbers between -5 and 5. Reshape into (4,5) array
#     and extract only the elements greater than 0.
print("\n Q5 extract only elements greater than 0")
ar5 = np.linspace(-5,5,20).reshape(4,5)
greater_zero = ar5[ar5 > 0]
print(ar5)
print()
print(greater_zero)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

 Q2 
 [[25 44 14 27 24]
 [48 13 41 12 39]
 [44 26 44 46 33]
 [41 15 20 23 25]
 [18 18 11 26 19]]

 Even num : [44 14 24 48 12 44 26 44 46 20 18 18 26]

 Q3 broadcasting to add b to each row of a 

[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]

 Q6 replace secondary diagonal (from top-right to bottom-left)
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]

[[1 0 0 0 0 7]
 [0 1 0 0 7 0]
 [0 0 1 7 0 0]
 [0 0 7 1 0 0]
 [0 7 0 0 1 0]
 [7 0 0 0 0 1]]

 Q5 extract only elements greater than 0
[[-5.         -4.47368421 -3.94736842 -3.42105263 -2.89473684]
 [-2.36842105 -1.84210526 -1.31578947 -0.78947368 -0.26315789]
 [ 0.26315789  0.78947368  1.31578947  1.84210526  2.36842105]
 [ 2.89473684  3.42105263  3.94736842  4.47368421  5.        ]]

[0.26315789 0.78947368 1.31578947 1.84210526 2.36842105 2.89473684
 3.42105263 3.94736842 4.47368421 5.        ]


In [ ]:
# Q6. Create 4 x 4 array with numbers from 1 to 16. Swap the first and last rows using slicing
print("\n Q6 Slicing to swap first and last rows")
ar6 = np.arange(1,17).reshape(4,4)
print(ar6,"\n")
ar6[[0,-1]] = ar6[[-1,0]] # [[0,-1]] -> 0 = first row , -1 = last row
print(ar6)

# Q7. Create 10 x 10 array with random floats between 0 and 1, then find the row with the maximum sum
print("\n Q6 Maximum sum")
ar7 = np.random.rand(10,10)
print(ar7)
print()
max_row = np.argmax(np.sum(ar7,axis=1))
print("\n Maximum sum row :",max_row)
print("Maximun sum row :",ar7[max_row])


 Q6 Slicing to swap first and last rows
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[13 14 15 16]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]

 Q6 Maximum sum
[[0.0196576  0.64430922 0.6374547  0.04924748 0.45318111 0.29233036
  0.49791735 0.16384892 0.35709776 0.79956648]
 [0.43508397 0.90594569 0.80422309 0.00800883 0.83450562 0.90440911
  0.28673735 0.00576592 0.56889693 0.22166552]
 [0.66416513 0.50765756 0.022056   0.52682877 0.22442919 0.72969035
  0.24982476 0.05114732 0.96258265 0.45402248]
 [0.94957634 0.45128051 0.11426464 0.3524716  0.7781105  0.01552668
  0.89169634 0.63906082 0.66307106 0.16503108]
 [0.44130783 0.34420689 0.62641261 0.56799936 0.06929025 0.53309575
  0.10814339 0.31942938 0.30366325 0.8445188 ]
 [0.86713025 0.09162301 0.40554746 0.3087861  0.25952427 0.52077846
  0.11731845 0.11794432 0.99883518 0.07958416]
 [0.7882493  0.30839345 0.37740475 0.18281647 0.81836203 0.62616343
  0.30479631 0.712387   0.09235632 0.59362751]
 [0.42129107 

In [ ]:
# Q8. Given arr = np.arange(1,26).reshape(5,5) , extract the sunmatrix of even numbers only keeping their 2d structure
print("Q8 Submatrix with ecen number")
ar8 = np.arange(1,26).reshape(5,5)
even_2d = np.where(ar8 % 2 ==0 , ar8 , 0)
print("\nSubmatrix with even number:\n",even_2d)

# Q9. Generate two arrays a = np.array([1,2,3]) and b = np.array([[10],[20],[30]]).
#     Perform amultiplication using broadcasting and explain the result
a1 = np.array([1,2,3])
a2 = np.array([[10],[20],[30]])
mul = a1 * a2
print("\nQ9 Multipilaction using broadcasting")
print("Multiplication using broadcasting :\n",mul)

# Q10. Create a diagonal matrix with values [5,10,15,20]. Then convert it into a full 4 x 4
#       where diagonal valus remain but others ard filled with -1
print("\n Q10 diagonal\n")
diag = [5,10,15,20]
ar10 = np.full((4,4),-1)
np.fill_diagonal(ar10,diag) # ar10-> array whose diagonal fill , diag->value to place on diagonal
print(ar10)

Q8 Submatrix with ecen number

Submatrix with even number:
 [[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]

Q9 Multipilaction using broadcasting
Multiplication using broadcasting :
 [[10 20 30]
 [20 40 60]
 [30 60 90]]

 Q10 diagonal

[[ 5 -1 -1 -1]
 [-1 10 -1 -1]
 [-1 -1 15 -1]
 [-1 -1 -1 20]]


In [ ]:
# Q11. Using np.eye(5). create 5 x 5 matrix with diagonal values equal to multiples of 3
print("Q11 diagonal value equal to multiples of 3 \n")
id = np.eye(5,dtype=int)
diag_value = np.arange(1,6) * 3
matrix = id * diag_value
print("\nMatrix with diagonal with multiple of 3 :\n",matrix)

# Q12.Construct an array of shape (3,4,2) with values from 1 to 24. Flatten it using ravel(), and then reshape it into (2,3,4).
print("\nQ12 flatten it using ravel()\n")
ar12 = np.arange(1,25).reshape(3,4,2)
print(ar12,"\n")
flat_arr = ar12.ravel()
print("\nFlatten array :\n",flat_arr)
reshape_arr12 = flat_arr.reshape(2,3,4)
print("\nAfter reshape :\n",reshape_arr12)


Q11 diagonal value equal to multiples of 3 


Matrix with diagonal with multiple of 3 :
 [[ 3  0  0  0  0]
 [ 0  6  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 12  0]
 [ 0  0  0  0 15]]

Q12 flatten it using ravel()

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]] 


Flatten array :
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

After reshape :
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [14]:
# Q13. Generate a 7×7 matrix of random integers (1–100). Replace all values divisible by 5 with -5 using boolean indexing.
print("Q13 \n")
ar13 = np.random.randint(1,100,(7,7))
print("Origial array :\n",ar13)
ar13[ar13 % 5 == 0 ] = -5
print("\nAfter replacing:\n",ar13)

# Q14 Given arr = np.linspace(0, 2*np.pi, 10), compute sine and cosine values for each element and stack them into a 2D array with shape (10,2)
print("\nQ14 Sin cos \n")
ar14 = np.linspace(0,2*np.pi,10)
print(ar14)
sin_value = np.sin(ar14)
cos_value = np.cos(ar14)
result = np.column_stack((sin_value,cos_value)) #(()) for used multiple argument
print("Sine and Cosine values :\n",result)

# Q15 Create a 5 X 5 checkboard pattern (alternating 0s and 1s) using slicing, without
#     manually typing each element
ar15 = np.zeros((5,5),dtype = int)
ar15[::2,::2] = 1 #set even row , even column
ar15[1::2,1::2] = 1 # set odd row , odd column
print("\nQ15 checkboard \n")
print(ar15)

Q13 

Origial array :
 [[20 48 93 57 22 59 88]
 [52 42 48  8 20 97 60]
 [81 85 57 38 94 47 96]
 [53 66 81 20 24 40 89]
 [74 17 47 38 15 96 60]
 [86 94 73 58  4 14  3]
 [34 29 98 27 99 79 52]]

After replacing:
 [[-5 48 93 57 22 59 88]
 [52 42 48  8 -5 97 -5]
 [81 -5 57 38 94 47 96]
 [53 66 81 -5 24 -5 89]
 [74 17 47 38 -5 96 -5]
 [86 94 73 58  4 14  3]
 [34 29 98 27 99 79 52]]

Q14 Sin cos 

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
Sine and Cosine values :
 [[ 0.00000000e+00  1.00000000e+00]
 [ 6.42787610e-01  7.66044443e-01]
 [ 9.84807753e-01  1.73648178e-01]
 [ 8.66025404e-01 -5.00000000e-01]
 [ 3.42020143e-01 -9.39692621e-01]
 [-3.42020143e-01 -9.39692621e-01]
 [-8.66025404e-01 -5.00000000e-01]
 [-9.84807753e-01  1.73648178e-01]
 [-6.42787610e-01  7.66044443e-01]
 [-2.44929360e-16  1.00000000e+00]]

Q15 checkboard 

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]
